project_id = "sqctfhfpuskjaziabtcv"

[functions.chat]
verify_jwt = true

[functions.search]
verify_jwt = true

[functions.process-pdf]
verify_jwt = true

[functions.ingest-dive-manual]
verify_jwt = true

[functions.init-dive-index]
verify_jwt = false
